title: Habituator
email: help.chapps@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A clean <b>habit tracker</b> for iOS, iPadOS and watchOS.

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://habituator.app" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "/habituator-website"
url: https://alaincaltieri.github.io

twitter_username: jekyllrb
github_username:  jekyll

theme_config:
  appearance: "auto"
  show_description: true

# Build settings
remote_theme: riggraz/no-style-please

plugins:
  - jekyll-feed
  - jekyll-seo-tag

screenshots:
  iPhone:
    - assets/media/AppStore/iPhone/xMax-01.png
    - assets/media/AppStore/iPhone/xMax-02.png
    - assets/media/AppStore/iPhone/xMax-03.png
    - assets/media/AppStore/iPhone/xMax-04.png
    - assets/media/AppStore/iPhone/xMax-05.png
    - assets/media/AppStore/iPhone/xMax-06.png
    - assets/media/AppStore/iPhone/xMax-07.png
    - assets/media/AppStore/iPhone/xMax-08.png
    - assets/media/AppStore/iPhone/xMax-09.png
  iPad:
    - assets/media/AppStore/iPad/iPad-01.png
    - assets/media/AppStore/iPad/iPad-02.png
    - assets/media/AppStore/iPad/iPad-03.png
    - assets/media/AppStore/iPad/iPad-04.png
    - assets/media/AppStore/iPad/iPad-05.png
    - assets/media/AppStore/iPad/iPad-06.png
    - assets/media/AppStore/iPad/iPad-07.png
    - assets/media/AppStore/iPad/iPad-08.png
    - assets/media/AppStore/iPad/iPad-09.png
  watch:
    - assets/media/AppStore/watchOS/watch-01.png
    - assets/media/AppStore/watchOS/watch-02.png
    - assets/media/AppStore/watchOS/watch-03.png
    - assets/media/AppStore/watchOS/watch-04.png
    - assets/media/AppStore/watchOS/watch-05.png
    - assets/media/AppStore/watchOS/watch-06.png
    
reviews:
  - author: ahpppppago
    title: Best Habit App Ever!
    text: LOVE the way you made this app it’s amazing I made so many lists and it’s more than just tracking for me it’s routines it’s goals They also update often and respond to concerns! 10/10 :)
    rating: 5
    country: United States
  - author: Sherylc6
    title:  Best habit app
    text: I’ve tried every habit app, and this is my favorite. The art and design is so cool. Marking habits is rewarding. I just use checklists for my required daily stuff, but habit apps are great for that “extra” stuff that you want to do to meet goals or get better at doing. I’ve found that I use this app most consistently- 5 stars! The one thing I’m not a fan of is the sound, which I turned off, but the unique icons make up for it.
    rating: 5
    country: United States
  - author: EmeraldJimmy
    title: Helps organise my day
    text: Like others using this app I have ADHD, and after trying many, many other apps, this one is easily the most effective for my needs.
    rating: 5
    country: United Kingdom
  - author: 노트매닉
    title: It’s awesome!!
    text: I enjoy this app very much every single day. This is so helpful for me to keep track on my daily life. I recommend this to everybody who wants to manage thier life in more organized fashion. Thanks for the developers of this app.
    rating: 5
    country: Korea, Republic of
  - author: okhhhferd
    title: Love it!
    text: I use the Lock Screen widget and the app helps me to keep track of key goals. Thank you for this useful app.
    rating: 5
    country: India
  - author: JoseLuisScorpio
    title: It is very good, intuitive and funny
    text: I really liked the way of creating the habits and simplicity that we can apply here, congrats!
    rating: 5
    country: Mexico

